### ISSUE TITLE
[Bug] In the exercise finale-workflow the function CertificateGeneratorWorkflow not really running 

### ISSUE THREAD

**Issue by ramiloif** [temporalio/edu-101-typescript-code#15]
### What are you really trying to do?

I tried to change the code inside the function : `CertificateGeneratorWorkflow`
in the file:  `exercises/finale-workflow/src/workflows.ts`
Just for learning purposes.
And I got to conclusion that the code inside there is not really running 

### Describe the bug

I changed  the code from: 
```
// The CertificateGeneratorWorkflow workflow calls the CreatePdf activity
export async function CertificateGeneratorWorkflow(name: string): Promise<string> {
  
// CreatePdf is the Activity Type defined in the implementation of the Java Activity code
  return await CreatePdf(name);
}
```
to 
```
// The CertificateGeneratorWorkflow workflow calls the CreatePdf activity
export async function CertificateGeneratorWorkflow(name: string): Promise<string> {
  
// CreatePdf is the Activity Type defined in the implementation of the Java Activity code
  return await "/test-learning/" + CreatePdf(name);
}
```
 And it did no effect on the result that stayed as it was

### Minimal Reproduction
Change the code as described above.

Another conclusion I have got to that I can delete the file : `exercises/finale-workflow/src/workflows.ts` completely
and in the `exercises/finale-workflow/src/client.ts` just change 
```
const handle = await client.workflow.start(CertificateGeneratorWorkflow, {
```
to
```
const handle = await client.workflow.start('CertificateGeneratorWorkflow', {
```

So this exercise not really demonstrate a way of invoke java activity from ts workflow.
It just invokes java workflow from ts client so it is missing the point.
### Environment/Versions

- OS and processor: [ M1 Mac]
- Temporal Version: [0.10.1]
- using Docker

**Comment by napcs** [comment]
@ramiloif Thanks for reporting this. I really appreciate the time you took to make such a detailed report. You're 100% correct that this wasn't working as intended. There's a fix rolling out soon.

**Comment by ramiloif** [comment]
🙌  thanks for the fix, great course
